const fs = require('fs');
const path = require('path');

const locales = ['en', 'te', 'hi', 'ta', 'kn', 'ml'];
const detailsEn = {
  "loading": "Decrypting Archive...",
  "notFound": "Archive entry not found.",
  "backButton": "[ESC] Return to Database",
  "archiveStatus": "Archive Status: SECURE",
  "forensicOverview": "Forensic Overview",
  "failureVectors": "Failure Vectors & Timeline",
  "timelineCapital": "CAPITAL DEPLOYMENT",
  "timelineCapitalDesc": "Initial architecture and funding sequence.",
  "timelineMarket": "MARKET FRICTION",
  "timelineMarketDesc": "Detected anomalies in market penetration.",
  "timelineTerminal": "TERMINAL SHUTDOWN",
  "timelineTerminalDesc": "System collapse and asset liquidation.",
  "terminalCause": "Terminal Failure Cause",
  "intelligenceSummary": "Strategic Intelligence Summary",
  "predictiveInsight": "Predictive Insight",
  "forensicVectorsFor": "Forensic vectors for",
  "indicateStructural": "indicate structural",
  "instability": "instability",
  "duringThe": "during the",
  "cycle": "cycle",
  "runSimulator": "Run Simulator",
  "marketMetrics": "Market Metrics",
  "saturationLoad": "Saturation Load",
  "criticalSaturation": "CRITICAL SATURATION",
  "statusVolatile": "STATUS: VOLATILE",
  "sectorMortality": "Sector Mortality",
  "ecosystem": "ECOSYSTEM"
};

const translations = {
  en: detailsEn,
  te: {
    "loading": "ఆర్కైవ్‌ను డీక్రిప్ట్ చేస్తోంది...",
    "notFound": "ఆర్కైవ్ నమోదు కనుగొనబడలేదు.",
    "backButton": "[ESC] డేటాబేస్‌కు తిరిగి వెళ్లండి",
    "archiveStatus": "ఆర్కైవ్ స్థితి: సురక్షితం",
    "forensicOverview": "ఫోరెన్సిక్ అవలోకనం",
    "failureVectors": "వైఫల్య వెక్టర్స్ & కాలక్రమం",
    "timelineCapital": "క్యాపిటల్ డిప్లాయ్‌మెంట్",
    "timelineCapitalDesc": "ప్రాథమిక ఆర్కిటెక్చర్ మరియు నిధుల క్రమం.",
    "timelineMarket": "మార్కెట్ ఘర్షణ",
    "timelineMarketDesc": "మార్కెట్ చొచ్చుకుపోవడంలో క్రమరాహిత్యాలు కనుగొనబడ్డాయి.",
    "timelineTerminal": "టెర్మినల్ షట్‌డౌన్",
    "timelineTerminalDesc": "సిస్టమ్ పతనం మరియు ఆస్తి పరిసమాప్తి.",
    "terminalCause": "టెర్మినల్ వైఫల్యానికి కారణం",
    "intelligenceSummary": "వ్యూహాత్మక ఇంటెలిజెన్స్ సారాంశం",
    "predictiveInsight": "ప్రిడిక్టివ్ ఇన్‌సైట్",
    "forensicVectorsFor": "దీని కోసం ఫోరెన్సిక్ వెక్టర్స్",
    "indicateStructural": "నిర్మాణాత్మకతను సూచిస్తాయి",
    "instability": "అస్థిరత",
    "duringThe": "ఈ సమయంలో",
    "cycle": "చక్రం",
    "runSimulator": "సిమ్యులేటర్‌ను అమలు చేయండి",
    "marketMetrics": "మార్కెట్ కొలమానాలు",
    "saturationLoad": "సంతృప్త లోడ్",
    "criticalSaturation": "క్రిటికల్ సంతృప్తత",
    "statusVolatile": "స్థితి: అస్థిరమైనది",
    "sectorMortality": "సెక్టార్ మరణాలు",
    "ecosystem": "పర్యావరణ వ్యవస్థ"
  },
  hi: {
    "loading": "पुरालेख डिक्रिप्ट किया जा रहा है...",
    "notFound": "पुरालेख प्रविष्टि नहीं मिली।",
    "backButton": "[ESC] डेटाबेस पर लौटें",
    "archiveStatus": "पुरालेख स्थिति: सुरक्षित",
    "forensicOverview": "फोरेंसिक अवलोकन",
    "failureVectors": "विफलता वैक्टर और समयरेखा",
    "timelineCapital": "पूंजी परिनियोजन",
    "timelineCapitalDesc": "प्रारंभिक वास्तुकला और वित्तपोषण अनुक्रम।",
    "timelineMarket": "बाजार घर्षण",
    "timelineMarketDesc": "बाजार में प्रवेश में विसंगतियों का पता चला।",
    "timelineTerminal": "टर्मिनल शटडाउन",
    "timelineTerminalDesc": "सिस्टम पतन और संपत्ति परिसमापन।",
    "terminalCause": "टर्मिनल विफलता का कारण",
    "intelligenceSummary": "रणनीतिक खुफिया सारांश",
    "predictiveInsight": "भविष्य कहनेवाला अंतर्दृष्टि",
    "forensicVectorsFor": "के लिए फोरेंसिक वैक्टर",
    "indicateStructural": "संरचनात्मक का संकेत देते हैं",
    "instability": "अस्थिरता",
    "duringThe": "के दौरान",
    "cycle": "चक्र",
    "runSimulator": "सिम्युलेटर चलाएं",
    "marketMetrics": "बाजार मेट्रिक्स",
    "saturationLoad": "संतृप्ति भार",
    "criticalSaturation": "महत्वपूर्ण संतृप्ति",
    "statusVolatile": "स्थिति: अस्थिर",
    "sectorMortality": "क्षेत्र मृत्यु दर",
    "ecosystem": "पारिस्थितिकी तंत्र"
  },
  ta: {
    "loading": "காப்பகத்தை மறைகுறியாக்குகிறது...",
    "notFound": "காப்பக உள்ளீடு கிடைக்கவில்லை.",
    "backButton": "[ESC] தரவுத்தளத்திற்குத் திரும்பு",
    "archiveStatus": "காப்பக நிலை: பாதுகாப்பானது",
    "forensicOverview": "தடயவியல் கண்ணோட்டம்",
    "failureVectors": "தோல்வி திசையன்கள் மற்றும் காலவரிசை",
    "timelineCapital": "மூலதன வரிசைப்படுத்தல்",
    "timelineCapitalDesc": "ஆரம்ப கட்டமைப்பு மற்றும் நிதி வரிசை.",
    "timelineMarket": "சந்தை உராய்வு",
    "timelineMarketDesc": "சந்தை ஊடுருவலில் முரண்பாடுகள் கண்டறியப்பட்டன.",
    "timelineTerminal": "முனைய பணிநிறுத்தம்",
    "timelineTerminalDesc": "அமைப்பு சரிவு மற்றும் சொத்து கலைப்பு.",
    "terminalCause": "முனைய தோல்வி காரணம்",
    "intelligenceSummary": "மூலோபாய நுண்ணறிவு சுருக்கம்",
    "predictiveInsight": "முன்கணிப்பு நுண்ணறிவு",
    "forensicVectorsFor": "இதற்கான தடயவியல் திசையன்கள்",
    "indicateStructural": "கட்டமைப்பு குறிப்பிடுகிறது",
    "instability": "நிலையற்ற தன்மை",
    "duringThe": "காலத்தில்",
    "cycle": "சுழற்சி",
    "runSimulator": "சிமுலேட்டரை இயக்கவும்",
    "marketMetrics": "சந்தை அளவீடுகள்",
    "saturationLoad": "செறிவு சுமை",
    "criticalSaturation": "சிக்கலான செறிவு",
    "statusVolatile": "நிலை: நிலையற்றது",
    "sectorMortality": "துறை இறப்பு",
    "ecosystem": "சுற்றுச்சூழல்"
  },
  kn: {
    "loading": "ಆರ್ಕೈವ್ ಅನ್ನು ಡಿಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "notFound": "ಆರ್ಕೈವ್ ನಮೂದು ಕಂಡುಬಂದಿಲ್ಲ.",
    "backButton": "[ESC] ಡೇಟಾಬೇಸ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    "archiveStatus": "ಆರ್ಕೈವ್ ಸ್ಥಿತಿ: ಸುರಕ್ಷಿತ",
    "forensicOverview": "ಫೋರೆನ್ಸಿಕ್ ಅವಲೋಕನ",
    "failureVectors": "ವೈಫಲ್ಯ ವಾಹಕಗಳು ಮತ್ತು ಟೈಮ್‌ಲೈನ್",
    "timelineCapital": "ಬಂಡವಾಳ ನಿಯೋಜನೆ",
    "timelineCapitalDesc": "ಆರಂಭಿಕ ವಾಸ್ತುಶಿಲ್ಪ ಮತ್ತು ಧನಸಹಾಯ ಅನುಕ್ರಮ.",
    "timelineMarket": "ಮಾರುಕಟ್ಟೆ ಘರ್ಷಣೆ",
    "timelineMarketDesc": "ಮಾರುಕಟ್ಟೆ ನುಗ್ಗುವಿಕೆಯಲ್ಲಿ ವೈಪರೀತ್ಯಗಳು ಕಂಡುಬಂದಿವೆ.",
    "timelineTerminal": "ಟರ್ಮಿನಲ್ ಸ್ಥಗಿತಗೊಳಿಸುವಿಕೆ",
    "timelineTerminalDesc": "ವ್ಯವಸ್ಥೆಯ ಕುಸಿತ ಮತ್ತು ಆಸ್ತಿ ದಿವಾಳಿ.",
    "terminalCause": "ಟರ್ಮಿನಲ್ ವೈಫಲ್ಯದ ಕಾರಣ",
    "intelligenceSummary": "ಕಾರ್ಯತಂತ್ರದ ಗುಪ್ತಚರ ಸಾರಾಂಶ",
    "predictiveInsight": "ಮುನ್ಸೂಚಕ ಒಳನೋಟ",
    "forensicVectorsFor": "ಇದಕ್ಕಾಗಿ ಫೋರೆನ್ಸಿಕ್ ವಾಹಕಗಳು",
    "indicateStructural": "ರಚನಾತ್ಮಕವನ್ನು ಸೂಚಿಸುತ್ತದೆ",
    "instability": "ಅಸ್ಥಿರತೆ",
    "duringThe": "ಸಮಯದಲ್ಲಿ",
    "cycle": "ಚಕ್ರ",
    "runSimulator": "ಸಿಮ್ಯುಲೇಟರ್ ಅನ್ನು ರನ್ ಮಾಡಿ",
    "marketMetrics": "ಮಾರುಕಟ್ಟೆ ಮೆಟ್ರಿಕ್ಸ್",
    "saturationLoad": "ಸ್ಯಾಚುರೇಶನ್ ಲೋಡ್",
    "criticalSaturation": "ನಿರ್ಣಾಯಕ ಶುದ್ಧತ್ವ",
    "statusVolatile": "ಸ್ಥಿತಿ: ಬಾಷ್ಪಶೀಲ",
    "sectorMortality": "ವಲಯದ ಮರಣ",
    "ecosystem": "ಪರಿಸರ ವ್ಯವಸ್ಥೆ"
  },
  ml: {
    "loading": "ആർക്കൈവ് ഡീക്രിപ്റ്റ് ചെയ്യുന്നു...",
    "notFound": "ആർക്കൈവ് എൻട്രി കണ്ടെത്തിയില്ല.",
    "backButton": "[ESC] ഡാറ്റാബേസിലേക്ക് മടങ്ങുക",
    "archiveStatus": "ആർക്കൈവ് നില: സുരക്ഷിതം",
    "forensicOverview": "ഫോറൻസിക് അവലോകനം",
    "failureVectors": "പരാജയ വെക്റ്ററുകളും സമയരേഖയും",
    "timelineCapital": "മൂലധന വിന്യാസം",
    "timelineCapitalDesc": "പ്രാഥമിക വാസ്തുവിദ്യയും ഫണ്ടിംഗ് ക്രമവും.",
    "timelineMarket": "വിപണി സംഘർഷം",
    "timelineMarketDesc": "വിപണിയിലെ നുഴഞ്ഞുകയറ്റത്തിൽ അപാകതകൾ കണ്ടെത്തി.",
    "timelineTerminal": "ടെർമിനൽ ഷട്ട്ഡൗൺ",
    "timelineTerminalDesc": "സിസ്റ്റം തകർച്ചയും ആസ്തി ലിക്വിഡേഷനും.",
    "terminalCause": "ടെർമിനൽ പരാജയ കാരണം",
    "intelligenceSummary": "സ്ട്രാറ്റജിക് ഇന്റലിജൻസ് സംഗ്രഹം",
    "predictiveInsight": "പ്രവചന ഉൾക്കാഴ്ച",
    "forensicVectorsFor": "ഇതിനായുള്ള ഫോറൻസിക് വെക്റ്ററുകൾ",
    "indicateStructural": "ഘടനാപരമായ സൂചിപ്പിക്കുന്നു",
    "instability": "അസ്ഥിരത",
    "duringThe": "സമയത്ത്",
    "cycle": "സൈക്കിൾ",
    "runSimulator": "സിമുലേറ്റർ പ്രവർത്തിപ്പിക്കുക",
    "marketMetrics": "മാർക്കറ്റ് മെട്രിക്സ്",
    "saturationLoad": "സാച്ചുറേഷൻ ലോഡ്",
    "criticalSaturation": "നിർണ്ണായക സാച്ചുറേഷൻ",
    "statusVolatile": "നില: അസ്ഥിരമാണ്",
    "sectorMortality": "സെക്ടർ മരണനിരക്ക്",
    "ecosystem": "ഇക്കോസിസ്റ്റം"
  }
};

locales.forEach(loc => {
  const filePath = path.join(__dirname, 'messages', `${loc}.json`);
  let content = {};
  if (fs.existsSync(filePath)) {
    content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  }
  content.ExploreDetails = translations[loc];
  fs.writeFileSync(filePath, JSON.stringify(content, null, 2));
});
console.log("Updated 6 message files with ExploreDetails translation.");
